### PR TITLE
Support container registries using Basic Auth

### PR DESCRIPTION
**Pull request by benwaffle**
**What this PR does / why we need it**:
Some container registries use just Basic auth to fetch images, instead of the Bearer token flow

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

**Please check the following list**:
- [ ]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [ ]  Does this change require a documentation update?
- [ ]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [ ]  Do all new files have an appropriate license header?

### CODE REVIEW

**Review by liulanzheng — APPROVED** [review]
LGTM

**Comment by liulanzheng** [comment]
@benwaffle  Would it be possible to also implement this feature in registryfs v1？

**Comment by benwaffle** [comment]
@liulanzheng sorry, I don't have the time to work on that right now

**Comment by liulanzheng** [comment]
@benwaffle  ok，let's not support v1 for now, and we can add it later. I will complete it when I have time, and it would be even better if you have time to do it as well.

**Pull request merged**
